In [21]:
from scipy.stats import kstest
import pandas as pd
import numpy as np

In [22]:
df=pd.DataFrame([np.random.normal(1,1,1000), np.random.normal(20,1,1000), np.random.normal(14,3,1000)]).T
df.columns=['a','b','c']

In [24]:
df.head()

          a          b          c
0  0.731642  20.101529  10.996889
1  0.713812  20.975077  15.967849
2  0.075708  19.451871  14.071577
3  1.972647  20.078764  11.005917
4  0.945036  18.162204  13.150056

In [25]:
#standardize the column

df.a=(df.a-df.a.mean())/df.a.std()

In [27]:
kstest(df.a,'norm')

#we canot reject the hypothesis that the column is normal

KstestResult(statistic=0.013565254189123355, pvalue=0.992838260683327)

In [52]:
#standardize the whole dataframe
(df-df.mean())/df.std()

            a         b         c
0   -0.285064  0.080808 -1.035414
1   -0.302999  0.972022  0.586067
2   -0.944837 -0.581989 -0.032480
3    0.963204  0.057582 -1.032469
4   -0.070422 -1.897737 -0.333071
5   -0.866163 -0.105812  0.644095
6   -0.245974  0.729373  0.770067
7   -0.307550 -0.816150  0.024829
8    1.318294 -0.813563  0.703493
9    1.311512  0.059508 -0.792483
10  -0.622733 -0.538388  0.410407
11   0.484500 -0.679521 -0.695584
12   0.453359  1.085682 -0.651912
13   0.817717  0.654746  0.888633
14   0.200063 -0.769903  0.424649
15  -0.418127 -2.732317 -0.873120
16   0.028314  0.151097 -0.231842
17  -1.003768 -0.826876  0.809074
18  -1.490895  1.030052 -1.967382
19   0.085720 -0.388539  0.601652
20  -0.309124 -0.050915  0.960626
21  -0.551409  0.760579 -0.274600
22  -1.866151 -0.919826 -0.780334
23   0.377859  1.661986  0.213970
24  -0.390322  0.576945 -0.722358
25  -1.105004  1.272972  1.741059
26   0.252317 -1.679028  0.487807
27   0.660419  0.369124 -1.181685
28  -0.990847 -1.373187  0.902004
29  -0.888971  0.141932 -0.927413
..        ...       ...       ...
970  0.581240  0.415923  0.487464
971  2.039546 -1.075370 -0.165604
972  2.713382  0.917552 -0.877788
973  1.836903 -0.304575 -0.604086
974  0.912960  0.249036 -0.569721
975 -1.254179 -1.249244  0.328239
976 -0.842380  0.057475  0.459660
977 -1.658794 -0.130427  0.660070
978 -1.814265 -0.918423  0.117772
979 -0.207310  0.008368  0.995658
980  0.334104 -0.754068 -0.133828
981 -0.344856 -0.205947 -0.672034
982  1.185697  1.527496  1.208645
983  0.193368  0.893105 -1.227025
984  1.074697 -1.245903  1.779565
985  0.531853 -1.621663  0.276562
986 -0.821445  0.510334 -1.345022
987 -0.225063 -1.788543  1.904364
988 -0.398597  1.036765  0.887918
989  0.540860 -1.448664  1.342014
990 -0.432896  0.251942 -0.105614
991  1.175405 -1.283703 -1.035696
992 -0.323844 -2.356775  1.419138
993 -1.821099  0.139093  0.209301
994 -0.985071 -1.969287  0.979946
995  2.169172 -0.353035  0.339186
996 -0.547397 -0.501285 -0.031736
997 -1.017819 -0.354936 -0.211502
998  0.517282  1.296818  0.016220
999  0.350566  1.738507  0.551557

[1000 rows x 3 columns]

In [54]:
for i in df:
    print(kstest(df[i],'norm'))

KstestResult(statistic=0.013565254189123355, pvalue=0.992838260683327)
KstestResult(statistic=1.0, pvalue=0.0)
KstestResult(statistic=0.9999219694141831, pvalue=0.0)